<a href="https://colab.research.google.com/github/kuragaa/ML-HSE-24/blob/main/Cats2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df_train = pd.read_csv("Data_train.csv", delimiter=',')
df_test = pd.read_csv("Data_test.csv", delimiter=',')

In [ ]:
df_train.head(5)

type    group          education      meal preparation course  score-1  \
0      wild  group B   some high school  standard          completed       63   
1  domestic  group C  bachelor's degree  standard               none       67   
2  domestic  group C       some college  standard          completed       69   
3  domestic  group B   some high school  standard               none       62   
4      wild  group E       some college   reduced               none       93   

   score-2  score-3  
0       67       67  
1       69       75  
2       90       88  
3       64       66  
4       90       83

In [ ]:
df_train.isna().sum()

type                   0
group                 20
education              0
meal                   0
preparation course     0
score-1                0
score-2                0
score-3                0
dtype: int64

In [ ]:
df_test.isna().sum()

type                   0
group                 12
education              0
meal                   0
preparation course     0
dtype: int64

In [ ]:
df_train['group'].unique()

array(['group B', 'group C', 'group E', 'group D', 'group A', nan],
      dtype=object)

In [ ]:
df_test['group'].unique()

array(['group D', 'group C', 'group B', 'group A', 'group E', nan],
      dtype=object)

In [ ]:
df_train['group'].fillna('a', inplace=True)
df_test['group'].fillna('a', inplace=True)

In [ ]:
df_train.isna().sum()

type                  0
group                 0
education             0
meal                  0
preparation course    0
score-1               0
score-2               0
score-3               0
dtype: int64

In [ ]:
df_train['group'].unique()

array(['group B', 'group C', 'group E', 'group D', 'group A', 'a'],
      dtype=object)

In [ ]:
df_train['Pass'] = df_train.apply(lambda x: 1 if ((x['score-1'] > 50) & (x['score-2'] > 50) & (x['score-3'] > 50)) else 0, axis=1)

In [ ]:
df_train.head(10)

type    group           education      meal preparation course  \
0      wild  group B    some high school  standard          completed   
1  domestic  group C   bachelor's degree  standard               none   
2  domestic  group C        some college  standard          completed   
3  domestic  group B    some high school  standard               none   
4      wild  group E        some college   reduced               none   
5      wild  group D  associate's degree  standard               none   
6      wild  group B    some high school   reduced               none   
7  domestic  group B    some high school  standard               none   
8  domestic  group E  associate's degree   reduced          completed   
9  domestic  group C  associate's degree  standard          completed   

   score-1  score-2  score-3  Pass  
0       63       67       67     1  
1       67       69       75     1  
2       69       90       88     1  
3       62       64       66     1  
4       93       90       83     1  
5       61       55       52     1  
6       48       52       45     0  
7       66       69       68     1  
8       83       86       88     1  
9       57       77       80     1

In [ ]:
len(df_train[df_train['Pass'] == 0])

145

In [ ]:
wild_cats = len(df_train[df_train['type'] == 'wild'])
domestic_cats = len(df_train[df_train['type'] == 'domestic'])

pass_wild_cats = len(df_train[(df_train['type'] == 'wild') & (df_train['Pass'] == 1)])
pass_domestic_cats = len(df_train[(df_train['type'] == 'domestic') & (df_train['Pass'] == 1)])

In [ ]:
print(wild_cats, domestic_cats, pass_wild_cats, pass_domestic_cats)

343 357 268 287


In [ ]:
np.abs(pass_wild_cats / wild_cats - pass_domestic_cats / domestic_cats)

0.022580460755730947

In [ ]:
len(df_train[(df_train['Pass'] == 0) & (df_train['education'] == 'high school')])

35

In [ ]:
len(df_train[(df_train['Pass'] == 1) & (df_train['type'] == 'wild') & (df_train['preparation course'] == 'none')])

152

In [ ]:
df_train['score-1'].median()

66.0

In [ ]:
untr_dom_cats = df_train[(df_train['preparation course'] == 'none') & (df_train['type'] == 'domestic')]
first_q = untr_dom_cats['score-3'].quantile(q=0.25, interpolation='lower')
third_q = untr_dom_cats['score-3'].quantile(q=0.75, interpolation='lower')
third_q - first_q

20

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   type                700 non-null    object
 1   group               700 non-null    object
 2   education           700 non-null    object
 3   meal                700 non-null    object
 4   preparation course  700 non-null    object
 5   score-1             700 non-null    int64 
 6   score-2             700 non-null    int64 
 7   score-3             700 non-null    int64 
 8   Pass                700 non-null    int64 
dtypes: int64(4), object(5)
memory usage: 49.3+ KB


In [ ]:
df_train_new = df_train_new = pd.get_dummies(df_train, columns=['type', 'group', 'education', 'meal', 'preparation course'], drop_first=True)

In [ ]:
df_train_new.shape

(700, 17)

In [ ]:
df_train_new.head()

score-1  score-2  score-3  Pass  type_wild  group_group A  group_group B  \
0       63       67       67     1       True          False           True   
1       67       69       75     1      False          False          False   
2       69       90       88     1      False          False          False   
3       62       64       66     1      False          False           True   
4       93       90       83     1       True          False          False   

   group_group C  group_group D  group_group E  education_bachelor's degree  \
0          False          False          False                        False   
1           True          False          False                         True   
2           True          False          False                        False   
3          False          False          False                        False   
4          False          False           True                        False   

   education_high school  education_master's degree  education_some college  \
0                  False                      False                   False   
1                  False                      False                   False   
2                  False                      False                    True   
3                  False                      False                   False   
4                  False                      False                    True   

   education_some high school  meal_standard  preparation course_none  
0                        True           True                    False  
1                       False           True                     True  
2                       False           True                    False  
3                        True           True                     True  
4                       False          False                     True

In [ ]:
df_test_new = pd.get_dummies(df_test, columns=['type', 'group', 'education', 'meal', 'preparation course'], drop_first=True)

In [ ]:
df_test_new.head()

type_wild  group_group A  group_group B  group_group C  group_group D  \
0       True          False          False          False           True   
1       True          False          False           True          False   
2       True          False           True          False          False   
3       True           True          False          False          False   
4      False          False           True          False          False   

   group_group E  education_bachelor's degree  education_high school  \
0          False                        False                  False   
1          False                        False                  False   
2          False                        False                  False   
3          False                        False                  False   
4          False                        False                  False   

   education_master's degree  education_some college  \
0                      False                    True   
1                       True                   False   
2                      False                    True   
3                      False                   False   
4                      False                    True   

   education_some high school  meal_standard  preparation course_none  
0                       False           True                     True  
1                       False          False                    False  
2                       False          False                    False  
3                       False          False                     True  
4                       False           True                    False

In [ ]:
df_train_new.columns

Index(['score-1', 'score-2', 'score-3', 'Pass', 'type_wild', 'group_group A',
       'group_group B', 'group_group C', 'group_group D', 'group_group E',
       'education_bachelor's degree', 'education_high school',
       'education_master's degree', 'education_some college',
       'education_some high school', 'meal_standard',
       'preparation course_none'],
      dtype='object')

In [ ]:
X_train = df_train_new[['type_wild', 'group_group A',
       'group_group B', 'group_group C', 'group_group D', 'group_group E',
       "education_bachelor's degree", 'education_high school',
       "education_master's degree", 'education_some college',
       'education_some high school', 'meal_standard',
       'preparation course_none']]
y_train = df_train_new['Pass']


In [ ]:
X_test = df_test_new[['type_wild', 'group_group A',
       'group_group B', 'group_group C', 'group_group D', 'group_group E',
       "education_bachelor's degree", 'education_high school',
       "education_master's degree", 'education_some college',
       'education_some high school', 'meal_standard',
       'preparation course_none']]

In [ ]:
# 4b
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier(max_depth=5, criterion='entropy')
clf = cross_val_score(model, X=X_train, y=y_train, cv=3, scoring='roc_auc')

In [ ]:
print(clf)

[0.67076669 0.69115991 0.63890766]


In [ ]:
print(clf.mean())

0.6669447508733223


In [ ]:
np.arange(2, 21, 1, dtype=int)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [ ]:
parameters = {
    'max_depth': np.arange(2, 21, 1, dtype=int)
}

In [ ]:
#6 a
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(DecisionTreeClassifier(criterion='entropy'), cv=3, scoring='roc_auc', param_grid=parameters)
clf.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(criterion='entropy'),
             param_grid={'max_depth': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])},
             scoring='roc_auc')

In [ ]:
clf.best_params_

{'max_depth': 2}

In [ ]:
#6b
df_train['cat_bio'] = df_train.apply(lambda x: (x['type'], x['group']), axis=1)

In [ ]:
df_test['cat_bio'] = df_test.apply(lambda x: (x['type'], x['group']), axis=1)

In [ ]:
df_train_new = pd.get_dummies(df_train, columns=['cat_bio', 'education', 'meal', 'preparation course'], drop_first=True)

In [ ]:
df_test_new = pd.get_dummies(df_test, columns=['cat_bio', 'education', 'meal', 'preparation course'], drop_first=True)

In [ ]:
df_test_new.head()

type    group  cat_bio_('domestic', 'group A')  \
0      wild  group D                            False   
1      wild  group C                            False   
2      wild  group B                            False   
3      wild  group A                            False   
4  domestic  group B                            False   

   cat_bio_('domestic', 'group B')  cat_bio_('domestic', 'group C')  \
0                            False                            False   
1                            False                            False   
2                            False                            False   
3                            False                            False   
4                             True                            False   

   cat_bio_('domestic', 'group D')  cat_bio_('domestic', 'group E')  \
0                            False                            False   
1                            False                            False   
2                            False                            False   
3                            False                            False   
4                            False                            False   

   cat_bio_('wild', 'a')  cat_bio_('wild', 'group A')  \
0                  False                        False   
1                  False                        False   
2                  False                        False   
3                  False                         True   
4                  False                        False   

   cat_bio_('wild', 'group B')  cat_bio_('wild', 'group C')  \
0                        False                        False   
1                        False                         True   
2                         True                        False   
3                        False                        False   
4                        False                        False   

   cat_bio_('wild', 'group D')  cat_bio_('wild', 'group E')  \
0                         True                        False   
1                        False                        False   
2                        False                        False   
3                        False                        False   
4                        False                        False   

   education_bachelor's degree  education_high school  \
0                        False                  False   
1                        False                  False   
2                        False                  False   
3                        False                  False   
4                        False                  False   

   education_master's degree  education_some college  \
0                      False                    True   
1                       True                   False   
2                      False                    True   
3                      False                   False   
4                      False                    True   

   education_some high school  meal_standard  preparation course_none  
0                       False           True                     True  
1                       False          False                    False  
2                       False          False                    False  
3                       False          False                     True  
4                       False           True                    False

In [ ]:
df_train_new.columns

Index(['type', 'group', 'score-1', 'score-2', 'score-3', 'Pass',
       'cat_bio_('domestic', 'group A')', 'cat_bio_('domestic', 'group B')',
       'cat_bio_('domestic', 'group C')', 'cat_bio_('domestic', 'group D')',
       'cat_bio_('domestic', 'group E')', 'cat_bio_('wild', 'a')',
       'cat_bio_('wild', 'group A')', 'cat_bio_('wild', 'group B')',
       'cat_bio_('wild', 'group C')', 'cat_bio_('wild', 'group D')',
       'cat_bio_('wild', 'group E')', 'education_bachelor's degree',
       'education_high school', 'education_master's degree',
       'education_some college', 'education_some high school', 'meal_standard',
       'preparation course_none'],
      dtype='object')

In [ ]:
fit_columns = ["cat_bio_('domestic', 'group A')", "cat_bio_('domestic', 'group B')",
       "cat_bio_('domestic', 'group C')", "cat_bio_('domestic', 'group D')",
       "cat_bio_('domestic', 'group E')", "cat_bio_('wild', 'a')",
       "cat_bio_('wild', 'group A')", "cat_bio_('wild', 'group B')",
       "cat_bio_('wild', 'group C')", "cat_bio_('wild', 'group D')",
       "cat_bio_('wild', 'group E')", "education_bachelor's degree",
       'education_high school', "education_master's degree",
       'education_some college', 'education_some high school', 'meal_standard',
       'preparation course_none']

In [ ]:
model = DecisionTreeClassifier(max_depth=5, criterion='entropy')
model.fit(X=df_train_new[fit_columns], y=df_train_new['Pass'])

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [ ]:
pred_proba = model.predict_proba(df_train_new[fit_columns])

In [ ]:
from sklearn.metrics import roc_auc_score

roc_auc_score(df_train_new['Pass'], pred_proba[:, 1])

0.7831438334886611

In [ ]:
# 6 в
df_train.columns

Index(['type', 'group', 'education', 'meal', 'preparation course', 'score-1',
       'score-2', 'score-3', 'Pass', 'cat_bio'],
      dtype='object')

In [ ]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=1000, max_depth=5)

model.fit(X_train, y_train)

Learning rate set to 0.008847
0:	learn: 0.6878530	total: 2.08ms	remaining: 2.07s
1:	learn: 0.6829921	total: 4.15ms	remaining: 2.07s
2:	learn: 0.6779150	total: 7.18ms	remaining: 2.38s
3:	learn: 0.6737483	total: 8.73ms	remaining: 2.17s
4:	learn: 0.6696127	total: 20.8ms	remaining: 4.14s
5:	learn: 0.6653994	total: 23.6ms	remaining: 3.91s
6:	learn: 0.6608347	total: 26.9ms	remaining: 3.81s
7:	learn: 0.6550397	total: 29ms	remaining: 3.59s
8:	learn: 0.6520855	total: 31.8ms	remaining: 3.5s
9:	learn: 0.6469967	total: 33.2ms	remaining: 3.29s
10:	learn: 0.6421652	total: 34.6ms	remaining: 3.11s
11:	learn: 0.6386342	total: 36.8ms	remaining: 3.03s
12:	learn: 0.6338860	total: 38.2ms	remaining: 2.9s
13:	learn: 0.6286509	total: 39.4ms	remaining: 2.77s
14:	learn: 0.6249533	total: 40.9ms	remaining: 2.68s
15:	learn: 0.6204672	total: 46.8ms	remaining: 2.88s
16:	learn: 0.6172191	total: 48.4ms	remaining: 2.8s
17:	learn: 0.6134207	total: 49.9ms	remaining: 2.72s
18:	learn: 0.6099876	total: 51.1ms	remaining: 2.6

In [ ]:
pred = model.predict_proba(X_test)

In [ ]:
pred

array([[0.28814817, 0.71185183],
       [0.48860327, 0.51139673],
       [0.16729732, 0.83270268],
       [0.34214838, 0.65785162],
       [0.00584793, 0.99415207],
       [0.0057044 , 0.9942956 ],
       [0.00573585, 0.99426415],
       [0.07853047, 0.92146953],
       [0.00893936, 0.99106064],
       [0.03627771, 0.96372229],
       [0.29856222, 0.70143778],
       [0.09515326, 0.90484674],
       [0.04720703, 0.95279297],
       [0.07853047, 0.92146953],
       [0.16372078, 0.83627922],
       [0.18656442, 0.81343558],
       [0.24846969, 0.75153031],
       [0.00914929, 0.99085071],
       [0.22907041, 0.77092959],
       [0.32826317, 0.67173683],
       [0.12872351, 0.87127649],
       [0.28995155, 0.71004845],
       [0.14228382, 0.85771618],
       [0.61755075, 0.38244925],
       [0.00240189, 0.99759811],
       [0.16139705, 0.83860295],
       [0.59991613, 0.40008387],
       [0.02125606, 0.97874394],
       [0.17465874, 0.82534126],
       [0.00366121, 0.99633879],
       [0.

In [ ]:
df_pred = pd.DataFrame(pred)

In [ ]:
df_pred

0
0    1
1    1
2    1
3    1
4    1
..  ..
295  1
296  1
297  1
298  0
299  1

[300 rows x 1 columns]

In [ ]:
df_pred.to_csv("result.txt", index=False, header=False)

In [ ]:
model.feature_importances_

array([15.1099999 ,  3.77896695,  3.3443264 ,  3.24433522,  5.05678091,
        3.78849215,  3.14918296,  4.38233983,  3.08448034,  4.28827922,
        7.03050829, 25.81324997, 17.92905785])